# Generated by Django 5.0 on 2023-12-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('shortDesc', models.TextField(max_length=255)),
                ('longDesc', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos_imagem/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('preco', models.FloatField()),
                ('precoPromocional', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
