# Generated by Django 5.0 on 2023-12-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_var'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='var',
            options={'verbose_name': 'Var', 'verbose_name_plural': 'Var'},
        ),
    ]
